[package]
name = "rusty_tracer"
version = "0.1.0"
authors = ["Moritz Roetner <moritz.roetner@ipm.fraunhofer.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.23.2"
approx = "0.4.0"