[package]
name = "rraytracer"
version = "0.1.0"
authors = ["Moritz <hallo@moritzroetner.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-iter = "0.1.39"